# Este es el manual de instrucciones para el servidor de Render.
# Garantiza que la página se construya y ejecute correctamente.

services:
  # Define el servicio web principal
  - type: web
    name: eldesconocido
    env: python
    plan: free # El plan gratuito
    
    # Comandos para construir y arrancar el servidor
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    
    # ¡LA CLAVE! Esto crea un "disco duro" persistente en el servidor.
    # Aquí se guardarán tu base de datos y las imágenes que subas,
    # asegurando que NO se borren con las actualizaciones.
    disks:
      - name: eldesconocido-data
        mountPath: /var/data/project_data
        sizeGB: 1
